### ISSUE TITLE
error in bot after Added to queue... command received

### ISSUE THREAD

**Issue by branchmaster** [viperadnan-git/video-encoder-bot#3]
Hi Adnan , 
I'm get an error below after Added to queue... command received in bot :
" expected str, bytes or os.PathLike object, not NoneType "
I'll try to set env var value for DOWNLOAD_DIR is empty & / but in both received eror too.
my application log for allprocess write below :

`021-04-23T07:40:57.420214+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-23T07:40:57.420215+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 509, in handle_download
2021-04-23T07:40:57.420215+00:00 app[worker.1]:     shutil.move(temp_file_path, final_file_path)
2021-04-23T07:40:57.420216+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/shutil.py", line 826, in move
2021-04-23T07:40:57.420216+00:00 app[worker.1]:     copy_function(src, real_dst)
2021-04-23T07:40:57.420216+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/shutil.py", line 435, in copy2
2021-04-23T07:40:57.420217+00:00 app[worker.1]:     copyfile(src, dst, follow_symlinks=follow_symlinks)
2021-04-23T07:40:57.420217+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/shutil.py", line 264, in copyfile
2021-04-23T07:40:57.420217+00:00 app[worker.1]:     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
2021-04-23T07:40:57.420218+00:00 app[worker.1]: OSError: [Errno 30] Read-only file system: '/video_2021-04-22_09-09-31_6954254937751912448.mp4'`

waiting for your response
finest regards

**Comment by zYxDevs** [comment]
change value of var `DOWNLOAD_DIR` to `downloads/`
